site_name: Titan Documentation
nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Hardware Architecture: hardware.md
  - Software Architecture: software.md
  - Robot Bringup: bringup.md
  - Visualization: visualization.md
  - Mapping: mapping.md
  - Localization and Navigation: navigation.md
  - Simulation: simulation.md
  - Networking and Remote Access: networking.md
  - Troubleshooting: troubleshoot.md
  - About: about.md
theme: readthedocs
docs_dir: docs
site_dir: site
