site_name: Titan Documentation
nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Hardware Architecture: hardware.md
  - Software Architecture: software.md
  - About: about.md
theme: readthedocs
docs_dir: docs
site_dir: site
